'use strict';
const form=document.querySelector('#object-form');
if(form){const photo=document.querySelector('#photo'),error=document.querySelector('#form-error');let previewURL;
photo.addEventListener('change',()=>{error.textContent='';const file=photo.files[0],preview=document.querySelector('#photo-preview');preview.hidden=true;document.querySelector('#photo-label').textContent='Choose a photo to remember it by';if(previewURL)URL.revokeObjectURL(previewURL);if(!file)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>5*1024*1024){error.textContent='Please choose a JPG, PNG, WebP or GIF smaller than 5 MB.';photo.value='';return}previewURL=URL.createObjectURL(file);preview.src=previewURL;preview.hidden=false;document.querySelector('#photo-label').textContent=file.name;});
form.addEventListener('submit',event=>{event.preventDefault();const name=form.elements.name.value.trim(),description=form.elements.description.value.trim();if(!name||!description){error.textContent='Give your belonging a name and tell us a little about it.';return}try{sessionStorage.setItem('bye-bye-letter',JSON.stringify({name,description}));const button=form.querySelector('button');button.disabled=true;button.setAttribute('aria-busy','true');button.textContent='Opening your letter…';document.body.classList.add('leaving');setTimeout(()=>{location.href='letter.html'},matchMedia('(prefers-reduced-motion: reduce)').matches?0:280)}catch{error.textContent='Your browser is blocking temporary storage. Allow it to open your letter.'}});}
const body=document.querySelector('#letter-body');if(body){try{const data=JSON.parse(sessionStorage.getItem('bye-bye-letter')||'null');if(data&&typeof data.name==='string'&&typeof data.description==='string'){document.querySelector('#letter-from').textContent='FROM: '+data.name.toUpperCase();body.replaceChildren();const description=data.description;const paragraphs=[`It’s me, ${data.name}. I know this is not where you expected to find me. But imagine this little letter travelling all the way back to you.`,`You remember me like this: “${description}” I like knowing that there is a version of me still safe inside your memory.`,`For now, imagine I have found a quiet place by a window. The light moves slowly here. Every afternoon feels like the beginning of a small adventure, and I am learning to be curious.`,`Our time together still belongs to us. You don’t have to stop missing me, and you don’t have to keep looking forever. There is room for both a little sadness and whatever lovely thing comes next.`,`If you think of me tomorrow, picture me somewhere with a breeze. I’ll be carrying a little of you, too.`];for(const text of paragraphs){const p=document.createElement('p');p.textContent=text;p.style.setProperty('--paragraph',body.childElementCount);body.append(p)}document.querySelector('#letter-signature').textContent=`Still yours, ${data.name}`;}}catch{}}

// Restore submit controls when navigating back from a cached letter page.
window.addEventListener('pageshow',()=>{document.body.classList.remove('leaving');if(form){const button=form.querySelector('button');button.disabled=false;button.removeAttribute('aria-busy');button.replaceChildren(document.createTextNode('Let it write back '));const arrow=document.createElement('span');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');button.append(arrow);}});
if('IntersectionObserver' in window && !matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}},{threshold:0.08});for(const section of document.querySelectorAll('.sample-intro')){section.classList.add('reveal');observer.observe(section);}}
